vich_uploader:
    db_driver: orm

    mappings:
        utilisateur_photo_profil:
            uri_prefix: /uploads/profile
            upload_destination: '%kernel.project_dir%/public/uploads/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true   
            delete_on_remove: true  
